#!/bin/bash
set -eu -o pipefail
safe_source () { [[ ! -z ${1:-} ]] && source $1; _dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; _sdir=$(dirname "$(readlink -f "$0")"); }; safe_source

safe_source "$_sdir/find-root.sh"

lsFile="$1"
shift 
set-pane-title () {
    title="$1"
    if { [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; } then
        # we are in a tmux session
        printf "\033k$title\033\\"
    else
        # normal terminal session
        echo -e '\033]2;'$title'\007'
    fi
}
set-pane-title ${lsFile%.ls}
lsc $lsFile "$@"

